#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

# shellcheck disable=SC2230
FILE_SPLITTER_HOME="$(cd "$(dirname "$(which "$0")")"/.. >/dev/null; pwd -P)"
CLASSPATH="$FILE_SPLITTER_HOME"/lib

function join_by {
  local IFS="$1"
  shift
  echo "$*"
}

# Download missing dependencies first
"$FILE_SPLITTER_HOME"/bin/get-dependencies

APP_JARS="$(echo "${CLASSPATH}"/*.jar)"
# shellcheck disable=SC2068
CLASSPATH_JARS="$(join_by ':' ${APP_JARS[@]})"
java -cp "$CLASSPATH_JARS" me.amanj.file.splitter.App "$@"
