#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

# shellcheck disable=SC2230
FILE_SPLITTER_HOME="$(cd "$(dirname "$(which "$0")")"/.. >/dev/null; pwd -P)"
CLASSPATH="$FILE_SPLITTER_HOME"/lib/

APP_JAR="$(echo "${CLASSPATH}"/file-splitter-*.jar)"

java -jar "$APP_JAR" "$@"
