language: scala

jdk: openjdk8

scala:
   - 2.13.0

services:
  - docker

before_install:
  ci/env-setup

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test it:test coverageReport package
  - echo yay | distribution/target/file-splitter-*-SNAPSHOT-dist/file-splitter-*/bin/splitter -i stdin -o stdout

after_success:
  - export CODECOV_TOKEN="a6285401-5805-47a3-af73-6dcc4ae675c7"
  - bash <(curl -s https://codecov.io/bash)

after_script:
  ci/env-teardown
