language: scala

jdk: openjdk8

scala:
   - 2.13.0

services:
  - docker

before_install:
  ci/env-setup

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test it:test coverageReport package
  - echo yay | distribution/target/file-splitter-*-SNAPSHOT-dist/file-splitter-*/bin/splitter -i stdin -o stdout
  - echo yay | distribution/target/file-splitter-*-SNAPSHOT-dist/file-splitter-*/bin/splitter -i stdin -o sftp://localhost:2222/upload --output-sftp-username bar --output-sftp-password baz
  - echo yay | distribution/target/file-splitter-*-SNAPSHOT-dist/file-splitter-*/bin/splitter -i stdin -o /user/root --output-hdfs-root-uri hdfs://localhost:9000 --output-hdfs-user root

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_script:
  ci/env-teardown
